name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Shanghai

          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_rss: yes
          plugin_rss_source: https://homeboyc.cn/index.xml
          plugin_rss_limit: 4
          plugin_calendar: yes
          plugin_calendar_limit: 2

          config_display: large
          
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
        